builds:
- id: connect-server
  dir: .
  main: ./cmd/connect/server/
  flags:
  - -tags
  - netgo
  - -trimpath
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.version={{.Env.CONNECT_SERVER_VERSION}}
- id: grpc-server
  dir: .
  main: ./cmd/grpc/server/
  flags:
  - -tags
  - netgo
  - -trimpath
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.version={{.Env.GRPC_SERVER_VERSION}}
- id: grpc-gateway
  dir: .
  main: ./cmd/grpc/gateway/
  flags:
  - -tags
  - netgo
  - -trimpath
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.version={{.Env.GATEWAY_VERSION}}
