version: "3"

services:
  grpc-server:
    image: "ko.local/server:latest"
    ports:
      - "50051:50051"
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "DB_PASSWORD=password"
      - "DB_NAME=clean-protobuf"
      - "DB_SSL_MODE=disable"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=clean-protobuf"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 10
